"""empty message

Revision ID: 35416ea07abf
Revises: b47c575b35e7
Create Date: 2024-01-20 14:27:40.606273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35416ea07abf'
down_revision: Union[str, None] = 'b47c575b35e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('question_type', sa.Integer(), nullable=True, comment='問題類型'))
    op.add_column('reply', sa.Column('option_title', sa.String(length=50), nullable=True, comment='選項名稱'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reply', 'option_title')
    op.drop_column('reply', 'question_type')
    # ### end Alembic commands ###
