"""empty message

Revision ID: 42700a615290
Revises: f2407deb13bd
Create Date: 2024-02-15 22:04:17.555831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42700a615290'
down_revision: Union[str, None] = 'f2407deb13bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reply_ibfk_1', 'reply', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reply_ibfk_1', 'reply', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
