"""empty message

Revision ID: 80fffa4af966
Revises: efc87a12ddee
Create Date: 2024-01-09 18:21:38.247418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80fffa4af966'
down_revision: Union[str, None] = 'efc87a12ddee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'order',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='問題順序(排序用)')
    op.alter_column('reply', 'individual_id',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False,
               existing_comment='答覆者ID')
    op.alter_column('reply', 'question_id',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reply', 'question_id',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('reply', 'individual_id',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True,
               existing_comment='答覆者ID')
    op.alter_column('question', 'order',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='問題順序(排序用)')
    # ### end Alembic commands ###
