"""empty message

Revision ID: b47c575b35e7
Revises: 80fffa4af966
Create Date: 2024-01-20 13:48:31.501056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47c575b35e7'
down_revision: Union[str, None] = '80fffa4af966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('image_url', sa.String(length=150), nullable=True, comment='圖片網址'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'image_url')
    # ### end Alembic commands ###
