"""empty message

Revision ID: efc87a12ddee
Revises: 
Create Date: 2024-01-09 15:50:59.561341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc87a12ddee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('form',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True, comment='表單名稱'),
    sa.Column('description', sa.String(length=150), nullable=True, comment='表單描述'),
    sa.Column('accepts_reply', sa.Boolean(), nullable=True, comment='是否接受回覆'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('form_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True, comment='問題名稱'),
    sa.Column('description', sa.String(length=150), nullable=True, comment='問題描述'),
    sa.Column('type', sa.Integer(), nullable=True, comment='問題類型'),
    sa.Column('is_required', sa.Boolean(), nullable=True, comment='是否為必填'),
    sa.Column('image_url', sa.String(length=150), nullable=True, comment='圖片網址'),
    sa.Column('order', sa.Integer(), nullable=True, comment='問題順序(排序用)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True, comment='選項名稱'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('individual_id', sa.String(length=40), nullable=True, comment='答覆者ID'),
    sa.Column('question_id', sa.String(length=40), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=150), nullable=True, comment='簡答/詳答的回覆'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('option')
    op.drop_table('question')
    op.drop_table('form')
    op.drop_table('user')
    # ### end Alembic commands ###
