"""empty message

Revision ID: f2407deb13bd
Revises: a0f4120d79ad
Create Date: 2024-01-27 16:49:27.412158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2407deb13bd'
down_revision: Union[str, None] = 'a0f4120d79ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortened_url',
    sa.Column('key', sa.String(length=40), nullable=False, comment='短網址'),
    sa.Column('link', sa.String(length=500), nullable=False, comment='導向的長網址(不含 domain)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortened_url')
    # ### end Alembic commands ###
