name: CD pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Pull Docker image from Dockerhub
        run: docker pull pschuang/formrrito-cicd-pipeline:latest
      - name: Delete the old docker container
        run: docker rm -f formrrito-cicd-pipeline-container || true
      - name: Run docker container
        run: docker run -d --name formrrito-cicd-pipeline-container -p 8000:8000 pschuang/formrrito-cicd-pipeline
